blogus_the_first/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path

from blog.views.ArticleDeleteView import ArticleDeleteView
from blog.views.CategoryCreateView import CategoryCreateView
from blog.views.CategoryDeleteView import CategoryDeleteView
from blog.views.CategoryListView import CategoryListView
from blog.views.CategoryUpdateView import CategoryUpdateView
from blog.views.IndexView import IndexView
from blog.views.LogInView import LogInView
from blog.views.ArticleCreateView import ArticleCreateView
from blog.views.ArticleListView import ArticleListView
from blog.views.ArticleReadView import ArticleReadView
from blog.views.ArticleUpdateView import ArticleUpdateView
from blog.views.BestArticlesView import BestArticlesView
from blog.views.LogOutView import LogOutView
from blog.views.SignUpView import SignUpView
from blog.views.TagCreateView import TagCreateView
from blog.views.TagDeleteView import TagDeleteView
from blog.views.TagListView import TagListView
from blog.views.TagUpdateView import TagUpdateView

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    path('login', LogInView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('signup', SignUpView.as_view(), name='signup'),
    path('articles', ArticleListView.as_view(), name='article_list'),
    path('article/<int:pk>', ArticleReadView.as_view(), name='article_read'),
    path('article/create', ArticleCreateView.as_view(), name='article_create'),
    path('article/update/<int:pk>', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('tags', TagListView.as_view(), name='tag_list'),
    path('tag/create', TagCreateView.as_view(), name='tag_create'),
    path('tag/update/<int:pk>', TagUpdateView.as_view(), name='tag_update'),
    path('tag/delete/<int:pk>', TagDeleteView.as_view(), name='tag_delete'),
    path('categories', CategoryListView.as_view(), name='category_list'),
    path('category/create', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
)

blog/models/ArticleCategory.py
from django.db.models import Model, ForeignKey, CASCADE

from blog.models.Article import Article
from blog.models.Category import Category


class ArticleCategory(Model):
    article = ForeignKey(Article, on_delete=CASCADE)
    category = ForeignKey(Category, on_delete=CASCADE)

    def __str__(self):
        return f'#{self.id} {self.article}, {self.category}'

blog/models/ArticleTag.py
from django.db.models import Model, ForeignKey, CASCADE

from blog.models.Article import Article
from blog.models.Tag import Tag


class ArticleTag(Model):
    article = ForeignKey(Article, on_delete=CASCADE)
    tag = ForeignKey(Tag, on_delete=CASCADE)

    def __str__(self):
        return f'{self.article}, {self.tag}'

blog/models/ArticleUser.py
from django.contrib.auth.models import User
from django.db.models import Model, CASCADE, ForeignKey

from blog.models.Article import Article


class ArticleUser(Model):
    article = ForeignKey(Article, on_delete=CASCADE)
    user = ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return f'{self.article}, {self.user}'

blog/forms/LogInForm.py
from django import forms


class LogInForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        max_length=320,
        required=True
    )

    password = forms.CharField(
        min_length=5,
        widget=forms.PasswordInput,
        required=True
    )

blog/views/ArticleCreateView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from extra_views import CreateWithInlinesView

from blog.forms.ArticleForm import ArticleForm
from blog.formsets.ArticleCategoryFormSet import ArticleCategoryFormSet
from blog.formsets.ArticleTagFormSet import ArticleTagFormSet
from blog.models.Article import Article
from blog.models.ArticleUser import ArticleUser


class ArticleCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateWithInlinesView):
    template_name = 'article_create.html'
    model = Article
    form_class = ArticleForm
    inlines = (ArticleTagFormSet, ArticleCategoryFormSet, )
    success_url = reverse_lazy('article_list')
    success_message = _('Successfully published an article.')

    def form_valid(self, form):
        article = form.save()
        article_user = ArticleUser(article=article, user=self.request.user)
        article_user.save()
        return super().form_valid(form)

blog/views/ArticleDeleteView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.utils.translation import gettext_lazy as _

from blog.models.Article import Article


class ArticleDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'article_delete.html'
    model = Article
    success_url = reverse_lazy('article_list')
    success_message = _('Successfully deleted the article.')

blog/views/ArticleListView.py
from django.views.generic import ListView

from blog.models.Article import Article


class ArticleListView(ListView):
    template_name = 'article_list.html'
    paginate_by = 5

    def get_queryset(self):
        tag = self.request.GET.get('tag')
        category = self.request.GET.get('category')

        object_list = Article.objects.all()

        if tag:
            object_list = object_list.filter(
                articletag__tag__name__icontains=tag
            )

        if category:
            object_list = object_list.filter(
                articlecategory__category__name__icontains=category
            )

        return object_list

blog/views/ArticleReadView.py
from django.contrib.auth.models import User
from markdown import markdown
from django.views.generic import DetailView

from blog.models.Article import Article
from blog.models.Category import Category
from blog.models.Tag import Tag


class ArticleReadView(DetailView):
    template_name = 'article_read.html'
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['safe_html_content'] = markdown(self.object.content)

        context['users'] = User.objects.all().filter(
            articleuser__article__pk=self.object.pk
        )

        context['categories'] = Category.objects.all().filter(
            articlecategory__article__pk=self.object.pk
        )

        context['tags'] = Tag.objects.all().filter(
            articletag__article__pk=self.object.pk
        )

        return context

blog/views/BestArticlesView.py
from django.views.generic import ListView

from blog.models.Article import Article

limit = 3


class BestArticlesView(ListView):
    http_method_names = ['get']
    template_name = 'best_articles.html'
    queryset = Article.objects.all()[:limit]

blog/views/CategoryCreateView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import gettext_lazy as _

from blog.models.Category import Category


class CategoryCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Category
    fields = ('name', )
    template_name = 'category_create.html'
    success_url = reverse_lazy('category_list')
    success_message = _('Category created successfully.')

blog/views/CategoryDeleteView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.utils.translation import gettext_lazy as _

from blog.models.Category import Category


class CategoryDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Category
    template_name = 'category_delete.html'
    success_url = reverse_lazy('category_list')
    success_message = _('Category successfully deleted.')

blog/views/CategoryListView.py
from django.views.generic import ListView

from blog.models.Category import Category


class CategoryListView(ListView):
    model = Category
    template_name = 'category_list.html'
    paginate_by = 6

blog/views/LogInView.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.urls import reverse_lazy
from django.views.generic import FormView
from django.utils.translation import gettext_lazy as _

from blog.forms.LogInForm import LogInForm


class LogInView(FormView):
    template_name = 'login.html'
    form_class = LogInForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            login(self.request, user)
            messages.add_message(
                self.request,
                messages.INFO,
                _('Welcome back %(user)s!') % {'user': user.username}
            )
            return super().form_valid(form)

        # TODO i18n
        form.add_error(
            None,
            _('Invalid credentials.')
        )

        return self.form_invalid(form)

blog/views/SignUpView.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import gettext_lazy as _


class SignUpView(SuccessMessageMixin, CreateView):
    template_name = 'signup.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    success_message = _('Thank you for creating an account!')

blog/views/TagCreateView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.utils.translation import gettext_lazy as _

from blog.models.Tag import Tag


class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Tag
    fields = ('name', )
    template_name = 'tag_create.html'
    success_url = reverse_lazy('tag_list')
    success_message = _('Tag successfully created.')

blog/views/TagDeleteView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import DeleteView
from django.utils.translation import gettext_lazy as _

from blog.models.Tag import Tag


class TagDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    template_name = 'tag_delete.html'
    model = Tag
    success_url = reverse_lazy('tag_list')
    success_message = _('Tag successfully deleted.')

blog/views/TagListView.py
from django.views.generic import ListView

from blog.models.Tag import Tag


class TagListView(ListView):
    template_name = 'tag_list.html'
    model = Tag
    paginate_by = 6

templates/article_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Create an article' %}</h1>

    <form class="card form" action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            <label class="form-field">
                {% if field.error %}
                    <span class="field-error">{{ field.error }}</span>
                {% endif %}
                <div class="form-label">
                    {{ field.label }}
                </div>
                {{ field }}
            </label>
        {% endfor %}

        {% for inline in inlines %}
            <div class="form-inline">
                {{ inline.management_form }}

                {% for form in inline.forms %}
                    <div class="form-field">
                        {{ form }}
                    </div>
                {% endfor %}
            </div>
        {% endfor %}

        <button class="form-submit" type="submit">{% trans 'Publish' %}</button>
    </form>

{% endblock %}

templates/article_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'All articles' %}</h1>

    {% if user.is_staff %}

        <div class="card">
            <a href="{% url 'article_create' %}">
                {% trans 'Make a new article' %}
            </a>
        </div>
    {% endif %}

    <form class="card form" action="" method="GET">
        <div class="card-title">
            {% trans 'Filters' %}
        </div>

        <label class="form-field">
            <div class="form-label">
                {% trans 'By tag' %}
            </div>
            <input type="search" name="tag">
        </label>

        <label class="form-field">
            <div class="form-label">
                {% trans 'By category' %}
            </div>
            <input type="search" name="category">
        </label>

        <button class="form-submit" type="submit">
            {% trans 'Search' %}
        </button>

    </form>

    <ul>
        {% for article in article_list %}
            <li class="article card">
                <h2 class="card-title">
                    <a href="{% url 'article_read' article.id %}">
                            {{ article.title }}
                    </a>
                </h2>

                <ul>
                    {% for articlecategory in article.articlecategory_set.all %}
                        <li>
                            {{ articlecategory.category }}
                        </li>
                    {% endfor %}
                </ul>

                <ul>
                    {% for articletag in article.articletag_set.all %}
                        <li>
                            {{ articletag.tag }}
                        </li>
                    {% endfor %}
                </ul>

                <ul>
                    {% for articleuser in article.articleuser_set.all %}
                        <li>
                            {{ articleuser.user }}
                        </li>
                    {% endfor %}
                </ul>

                <p class="card-content article-preview">
                    {{ article.content }}
                </p>
            </li>
        {% endfor %}
    </ul>

    <nav class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; {% trans 'first' %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </nav>

{% endblock %}

templates/article_read.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

    {% if user.is_staff %}
        <div class="card">
            <a href="{% url 'article_update' object.id %}">
                {% trans 'Edit' %}
            </a>

            <a href="{% url 'article_delete' object.id %}">
                {% trans 'Delete' %}
            </a>
        </div>
    {% endif %}

    <article>
        <h1>{{ object.title }}</h1>

        <figure>
            <figcaption class="inline">
                {% trans 'Written by:' %}
            </figcaption>
            <ul class="inline-list">
                {% for writer in users %}
                    <li class="inline-list-comma">{{ writer }}</li>
                {% endfor %}
            </ul>
        </figure>

        <div class="card aside">

            <figure>
                <figcaption>{% trans 'Categories' %}</figcaption>
                <ul>
                    {% for category in categories %}
                        <li>
                            {{ category }}
                        </li>
                    {% endfor %}
                </ul>
            </figure>

            <figure>
                <figcaption>{% trans 'Tags' %}</figcaption>
                <ul>
                    {% for tag in tags %}
                        <li>
                            {{ tag }}
                        </li>
                    {% endfor %}
                </ul>
            </figure>

        </div>

        <main>
            {{ safe_html_content |safe }}
        </main>
    </article>
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
{% get_current_language as language_code %}
<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>
    <meta charset="utf-8" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <link rel="stylesheet" href="{% static 'index.css' %}" />

    <title>{{ title }}</title>
</head>
<body>
    {% block nav %}
        <nav class="nav">
            <ul class="content nav-list">
                {% block nav_links %}
                    <li>
                        <a href="{% url 'index' %}">
                            {% trans 'Home' %}
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'article_list' %}">
                            {% trans 'Articles' %}
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'category_list' %}">
                            {% trans 'Categories' %}
                        </a>
                    </li>

                    <li>
                        <a href="{% url 'tag_list' %}">
                            {% trans 'Tags' %}
                        </a>
                    </li>

                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url 'logout' %}">
                                {% trans 'Log out' %}
                            </a>
                        </li>

                    {% else %}
                        <li>
                            <a href="{% url 'login' %}">
                                {% trans 'Log in' %}
                            </a>
                        </li>

                        <li>
                            <a href="{% url 'signup' %}">
                                {% trans 'Sign up' %}
                            </a>
                        </li>
                    {% endif %}

                {% endblock %}
            </ul>
        </nav>

    {% endblock %}

    <main class="content">
        {% block messages %}
            {% if messages %}
                <aside>
                    <h1 class="messages-header">
                        {% trans 'Messages' %}
                    </h1>
                    <ul class="messages-list">
                        {% for message in messages %}
                            <li class="card">
                                {{ message }}
                            </li>
                        {% endfor %}
                    </ul>
                </aside>
            {% endif %}
        {% endblock %}

        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/best_articles.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Best articles' %}</h1>

    <ul>
    {% for article in article_list %}
        <li class="article card">
                <h2 class="card-title">
                    <a href="{% url 'article_read' article.id %}">
                            {{ article.title }}
                    </a>
                </h2>

                <p class="card-content article-preview">
                    {{ article.content }}
                </p>
            </li>
    {% endfor %}
    </ul>

{% endblock %}

templates/category_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Create a category' %}</h1>

    <form class="card form" action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            <label class="form-field">
                {% if field.error %}
                    <span class="field-error">{{ field.error }}</span>
                {% endif %}
                <div class="form-label">
                    {{ field.label }}
                </div>
                {{ field }}
            </label>
        {% endfor %}

        <button class="form-submit" type="submit">{% trans 'Publish' %}</button>
    </form>

{% endblock %}

templates/category_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>
        {% trans 'Do you really want to delete this category?' %}
    </h1>

    <p>
        {% trans 'There will be no going back!' %}
    </p>


    <form class="card form" action="" method="post">

        <p>
            {{ object.name }}
        </p>

        {% csrf_token %}

        <button class="form-submit" type="submit">
            {% trans 'Delete' %}
        </button>
    </form>

{% endblock %}

templates/category_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'All categories' %}</h1>

    {% if user.is_staff %}
        <div class="card">
            <a href="{% url 'category_create' %}">
                Create
            </a>
        </div>
    {% endif %}

    <ul>
        {% for object in object_list %}
            <li class="article card">
                {{ object.name }}

                <a href="{% url 'category_update' object.id %}">
                    {% trans 'Edit' %}
                </a>

                <a href="{% url 'category_delete' object.id %}">
                    {% trans 'Delete' %}
                </a>
            </li>
        {% endfor %}
    </ul>

    <nav class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; {% trans 'first' %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </nav>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
    <p>Hello</p>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>
        {% trans 'Log in' %}
    </h1>

    {% if form.errors %}
        <ul class="no-list card form-error">
            {% for error in form.non_field_errors %}
                <li>
                    {{ error }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    <form class="form card" action="" method="POST">
        {% csrf_token %}

        {% for field in form %}
            <label class="form-field">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <span class="field-error">{{ error }}</span>
                    {% endfor %}
                {% endif %}
                <div class="form-label">
                    {{ field.label }}
                </div>
                {{ field }}
            </label>
        {% endfor %}

        <input class="form-submit" type="submit" />
    </form>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>
        {% trans 'Sign up' %}
    </h1>

    <form class="card form" action="" method="POST">
        {% csrf_token %}

        {% if form.errors %}
            <ul class="form-error">
                {% for error in form.non_field_errors %}
                    <li>
                        {{ error }}
                    </li>
                {% endfor %}
            </ul>
        {% endif %}

        {% for field in form %}
            <label class="form-field">

                <div class="form-label">
                    {{ field.label }}
                </div>

                {{ field }}

                {% if field.errors %}
                    <ul class="form-error">
                        {% for error in field.errors %}
                            <li class="form-field-error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <div class="form-help-text">
                    {{ field.help_text }}
                </div>

            </label>

        {% endfor %}

        <input class="form-submit" type="submit" />
    </form>
{% endblock %}

templates/tag_create.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>{% trans 'Create a tag' %}</h1>

    <form class="card form" action="" method="post">
        {% csrf_token %}
        {% for field in form %}
            <label class="form-field">
                {% if field.error %}
                    <span class="field-error">{{ field.error }}</span>
                {% endif %}
                <div class="form-label">
                    {{ field.label }}
                </div>
                {{ field }}
            </label>
        {% endfor %}
        <button class="form-submit" type="submit">{% trans 'Publish' %}</button>
    </form>

{% endblock %}

templates/tag_delete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>
        {% trans 'Do you really want to delete this tag?' %}
    </h1>

    <p>
        {% trans 'There will be no going back.' %}
    </p>


    <form class="card form" action="" method="post">
        <h2>
            {{ object.name }}
        </h2>

        {% csrf_token %}

        <button class="form-submit" type="submit">
            {% trans 'Delete' %}
        </button>
    </form>

{% endblock %}

templates/tag_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>
        {% trans 'All tags' %}
    </h1>

    {% if user.is_staff %}
        <div class="card">
            <a href="{% url 'tag_create' %}">
                {% trans 'Create' %}
            </a>
        </div>

    {% endif %}

    <ul>
        {% for object in object_list %}
            <li class="article card">
                {{ object.name }}
                {% if user.is_staff %}
                    <a href="{% url 'tag_update' object.id %}">Edit</a>
                    <a href="{% url 'tag_delete' object.id %}">Delete</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <nav class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; {% trans 'first' %}</a>
                <a href="?page={{ page_obj.previous_page_number }}">{% trans 'previous' %}</a>
            {% endif %}

            <span class="current">
                {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </nav>

{% endblock %}